Adding Flatbuffers content-type
grpc/grpc-swift pull request #1141
Opened 2021-02-17 15:56 UTC by mustiikhalil

The following PR adds the ability to send custom "implemented" content-types `application/grpc+{(proto || flatbuffers)}`. It does that by checking the `customMetadata` object for the type `content-type` on the sender side, If there is an object of type content-type we use that as the `content-type` for the request. However if `customMetadata` doesn't have any header for the content-type we default to `application/grpc`. 

- Tests implemented:
     - Checks for sending custom content-types and if they would be appended in the header
     - Checks if the server would be able to parse those content types.
Notes: Tests were implemented on the valid server state only.

2021-02-17 16:50 UTC, glbrntt requested changes
Looks good so far, just a couple of nits in tests.

> Checks if the server would be able to parse those content types.

This isn't actually tested; you're testing receiving response headers from the server. `HTTP2ToRawGRPCStateMachineTests` is what you're after.

2021-02-17 16:50 UTC, glbrntt commented on Tests/GRPCTests/GRPCClientStateMachineTests.swift
> +  func testSendingDefaultContentypeRequestHeader() {
nit: `Contentype` -> `ContentType`

2021-02-17 16:50 UTC, glbrntt commented on Tests/GRPCTests/GRPCClientStateMachineTests.swift
> +  func testSendingProtoContentypeRequestHeader() {
nit: let's have a helper test which takes a `ContentType`, something like:

```swift
func doTestCustomContentType(_ contentType: ContentType) {
  var stateMachine = ...
  stateMachine.sendRequestHeaders(requestHead: .init(
    ...
    customMetadata: ["content-type": contentType.canonicalValue]
    ...
  )).assertSuccess { 
    ...
  } 
}
```

then we can just call that from our tests with `.flatbuffers` and `.protobuf`

2021-02-17 16:54 UTC, mustiikhalil commented
Thanks for the review! Yeah I was looking for that test class so I can see how to implement items there!

2021-02-18 00:45 UTC, mustiikhalil commented
converted to draft until the outcome of what's explained here https://github.com/grpc/grpc-swift/issues/1137#issuecomment-780951438

2021-09-11 19:17 UTC, mustiikhalil commented
Closing this since the go lang added a `ForceServerCodec`. Until the main grpc team fixes the issue with the headers not being sent properly. 

ref:
https://github.com/grpc/grpc/issues/25478

2021-09-11 19:17 UTC, closed without merging