Add setting for max number of concurrent streams for HTTP/2 connection
grpc/grpc-swift pull request #1226
Opened 2021-07-17 19:41 UTC by qusc

... in order to circumvent the limitation of a maximum of 100 concurrent calls as imposed by the default settings of NIOHTTP2Handler.

2021-07-19 10:29 UTC, glbrntt requested changes
Thanks for the PR, this broadly looks good! I left a few notes inline but I think we'll also want a test for this. It could do something like:

1. start a server setting max concurrent streams to N (where N > 100)
2. connect to the server
3. start N client streaming (or bidirectional streaming) RPCs
4. send a message on each RPC (but do not send end)
5. send end on RPC N
6. wait for the status on RPC N (i.e. if this RPC does not complete then we didn't apply the setting correctly)
7. send on all other RPCs, wait for them to complete

2021-07-20 08:56 UTC, qusc commented
@glbrntt awesome, thanks for your comments, let me know what you think about my changes

2021-07-20 12:09 UTC, glbrntt requested changes
This looks great! We're just missing a bit of resource cleanup in the tests then this should be good to go.

2021-07-20 12:09 UTC, glbrntt commented on Tests/GRPCTests/HTTP2MaxConcurrentStreamsTests.swift
> +    let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: System.coreCount)
Could you add a `defer` block here to shutdown the event loop group?

2021-07-20 12:09 UTC, glbrntt commented on Tests/GRPCTests/HTTP2MaxConcurrentStreamsTests.swift
> +      .wait()
Same here, can you add a `defer` block for shutting down the server?

2021-07-20 12:09 UTC, glbrntt commented on Tests/GRPCTests/HTTP2MaxConcurrentStreamsTests.swift
> +      .connect(host: "localhost", port: server.channel.localAddress!.port!)
And one more `defer` here to close the connection

2021-07-20 12:38 UTC, glbrntt approved these changes
Great, thank you @qusc! 🙏

2021-07-20 12:39 UTC, merged