Use #fileID/#filePath instead of #file
grpc/grpc-swift pull request #1518
Opened 2022-11-03 10:56 UTC by carolinacass

Motivation:

#fileID introduced in Swift 5.3, so no longer need to use #file anywhere                                  

Modifications:

Changed #file to #filePath or #fileID depending on the situation

2022-11-08 12:03 UTC, glbrntt requested changes

2022-11-08 12:03 UTC, glbrntt commented on Sources/Examples/RouteGuide/Client/RouteGuideClient.swift
> +  let url = URL(fileURLWithPath: #fileID)
This one should be `#filePath` as we're finding a file relative to this source file.

```suggestion
  let url = URL(fileURLWithPath: #filePath)
```

2022-11-08 12:03 UTC, glbrntt commented on Sources/Examples/RouteGuide/Server/RouteGuideServer.swift
> +  let url = URL(fileURLWithPath: #fileID)
Same here: 
```suggestion
  let url = URL(fileURLWithPath: #filePath)
```

2022-11-08 16:01 UTC, glbrntt commented
Thanks @carolinacass!

2022-11-08 16:11 UTC, merged

2022-11-11 08:58 UTC, Tharolzakariya commented on Sources/Examples/RouteGuide/Server/RouteGuideServer.swift
> +  let url = URL(fileURLWithPath: #fileID)
Withdraw