[CodeGenLib] Translator for enums containing type aliases and static properties
grpc/grpc-swift pull request #1733
Opened 2023-12-05 13:59 UTC by stefanadranca

Motivation:

In the generated code we want to have:

- enums for each namespace containing enums for all their services
- enums for each service (inside the corresponding namespace enum) containing
enums for all their methods, an array of all corresponding MethodDescriptors and type aliases for streaming and non-streaming protocols
- enums for each method (inside the corresponding service enum) containing
type aliases for the input and output types and a method descriptor (GRPCCore)

Modifications:

- created the Translator protocol defining the 'translate()' function.
- implemented the IDLToStructuredSwiftTranslator struct which conforms to the Translator protocol and creates the StructuredSwiftRepresentation for a CodeGenerationRequest calling the Specialized translators' functions.
- created the SpecializedTranslator protocol.
- implemented the TypeAliasTranslator, the first of the 3 SpecializedTranslators that takes in a CodeGenerationRequest object and creates all the enums, type aliases and properties mentioned in the Motivation, in StructuredSwiftRepresentation format.

TO DO:
- Snippet tests

Result:

The generated code will contain useful type aliases for message types and
protocol names, organized in namespace, service and method specific enums.

2023-12-05 14:03 UTC, stefanadranca commented on Sources/GRPCCodeGen/Internal/Translator/Translator.swift
> +    //    visibility: Visibility,
the Visibility type will be defined in the SourceGenerator API, which is not implemented yet.

2023-12-05 15:57 UTC, glbrntt commented on Sources/GRPCCodeGen/Internal/Translator/TypeAliasTranslator.swift
> +    var namespaceEnumDescription = EnumDescription(name: namespace)
nit: we can shorten this name (and others) to `namespaceEnum`

2023-12-06 09:34 UTC, glbrntt commented on Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
> +      ImportDescription(moduleName: "SwiftProtobuf"),
That's right, `SwiftProtobuf` and `WhateverModuleWeAddProtobufSerializersToo` will come as imports in the code gen request.

2023-12-06 13:42 UTC, glbrntt requested changes

2023-12-06 13:42 UTC, glbrntt commented on Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
> +  func makeNamespaceTypealiasesEnum(
Also given this is the typealias translator, we can drop that from all of these method names

2023-12-06 13:42 UTC, glbrntt commented on Tests/GRPCCodeGenTests/Internal/Translator/SnippetBasedTranslatorTests.swift
> +                      method: Collect
This isn't correct, these should be strings:
```suggestion
                      service: "echo.Echo",
                      method: "Collect"
```

2023-12-06 13:42 UTC, glbrntt commented on Tests/GRPCCodeGenTests/Internal/Translator/SnippetBasedTranslatorTests.swift
> +  func testTypealiasTranslate() throws {
This test is much bigger than is necessary, it's also not sufficient as a test.

Here are a handful of tests I thought of and what each is checking.
- One service in a namespace with one method. ("basic" case)
- One service with an _empty_ namespace and one method. (Checks that an empty namespace is treated as no namespace)
- One service in a namespace with two methods. (Checks order of methods is preserved). 
- One service in a namespace with no methods. (A valid edge case)
- Two services in the same namespace each with no methods where the services are in reverse alphabetical order in the request. (Checks that the services are ordered alphabetically within a namespace)
- Two services, both with empty namespaces, each with no methods. (Checks that the services are ordered alphabetically even when there's no namespace.)
- Two services in different namespaces each with no methods where the namespaces are in reverse alphabetical order in the request. (Checks that the namespaces are ordered alphabetically)
- Two services, one in a namespace, one not in a namespace, each with no methods. (Checks the order of namespace vs. no namespace)

There's also a handful of additional validation tests we can do:
- Two services with the same name and no namespace throws an error
- Two services with the same name and same namespace throws an error
- Two methods with the same name in a service throws an error

2023-12-06 13:42 UTC, glbrntt commented on Tests/GRPCCodeGenTests/Internal/Translator/SnippetBasedTranslatorTests.swift
> +  func _assertTypealiasTranslation(
This shouldn't need to be prefixed with an underscore. It can also be `private`.

2023-12-08 14:34 UTC, glbrntt requested changes

2023-12-08 14:34 UTC, glbrntt commented on Tests/GRPCCodeGenTests/Internal/Translator/SnippetBasedTranslatorTests.swift
> +              static let methods: [MethodDescriptor] = []
We should still generate an empty `Methods` enum

2023-12-08 14:34 UTC, glbrntt commented on Tests/GRPCCodeGenTests/Internal/Translator/SnippetBasedTranslatorTests.swift
> +      enum anamespace {
This highlights another potential issue: a service with no namespace can't have the same name as another namespace in the request. We'll need a test for this too.

2023-12-08 14:34 UTC, glbrntt commented on Tests/GRPCCodeGenTests/Internal/Translator/SnippetBasedTranslatorTests.swift
> +    self.assertThrowsError(try translator.translate(from: codeGenerationRequest)) {
Just copy this from the core-tests: https://github.com/grpc/grpc-swift/blob/79865359b894e8334e0d3b520294ceb2dfc7bcfd/Tests/GRPCCoreTests/Test%20Utilities/XCTest%2BUtilities.swift#L40-L51

2023-12-08 14:34 UTC, glbrntt commented on Tests/GRPCCodeGenTests/Internal/Translator/SnippetBasedTranslatorTests.swift
> +    )
You don't need this, just pass `serviceA` twice

2023-12-11 11:53 UTC, glbrntt requested changes

2023-12-11 11:53 UTC, glbrntt commented on Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
> +  private func makeServiceEnum(
This is much simpler now!

2023-12-11 16:25 UTC, glbrntt approved these changes

2023-12-11 16:31 UTC, merged