BenchmarkClient RPCs implementation
grpc/grpc-swift pull request #1861
Opened 2024-04-17 13:33 UTC by stefanadranca

Motivation:

When the WorkerService holds and monitors BenchmarkClients, they need to make the requests to the server, as configured in the config input the WorkerService receives from the Test Driver.

Modifications:

- implemented a helper function that computes the latency and extracts the error code for a RPC
- implemented the body of the makeRPC function that makes one of the 5 possible RPCs (implemented the RPCs)

Result:

The BenchmarkClient implementation for performance testing will be completed.

2024-04-17 15:06 UTC, glbrntt requested changes

2024-04-17 15:06 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +  private func computeTimeAndErrorCode<Contents>(
It's a bit strange to link the timing with the capturing of error codes. Aim for simple: have a function do one thing; time the execution of the body and return the result:

```swift
func timeIt<R>(_ body: () async throws -> R) async rethrows -> (R, seconds: Double) {
  // ...
}
```

This means at the call site you can return through the error code if applicable:

```swift
let (errorCode, seconds) = await timeIt { 
  do {
    try await client.whatever() 
    return nil
  } catch let error as RPCError {
    return error.code
  } catch {
    return .unknown
  }
}
```

2024-04-17 15:06 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +          return response.accepted
No need to return `accepted` here, we'll throw any `RPCError` from `response.message`, so if you get to the `return` here you know there's been no error.

Effectively we know that if we don't throw that the error code should be `nil`.

2024-04-17 15:06 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +        }
We need to consume the messages on the response: if we don't consume them we'll exert backpressure and the server will stop writing messages.

2024-04-17 15:06 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +          return response.accepted
Same note here re: consuming the messages

2024-04-17 15:28 UTC, stefanadranca commented on Sources/performance-worker/BenchmarkClient.swift
> +      $0.responseSize = 10
no particular reason, I was thinking we can create it a single time and set a random size. Is there a specific size I should set?

2024-04-17 15:31 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +      $0.responseSize = 10
Hmm, does the client config not tell us what size to use?

2024-04-17 15:37 UTC, stefanadranca commented on Sources/performance-worker/BenchmarkClient.swift
> +      $0.responseSize = 10
you're right, I forgot about the SimpleProtoParams - they specify the request and response sizes

2024-04-18 15:13 UTC, glbrntt requested changes
A few nits but looks good otherwise!

2024-04-18 15:13 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +  enum RpcType: Int {
nit: `RPCType`, also no need for it to be raw representable as an `Int` here

2024-04-18 15:13 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +    }
Can we do this _before_ creating the client?

2024-04-18 15:13 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +              rpcType: self.rpcType
We don't need to pass this in because it's stored on `self`

2024-04-18 15:13 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +    let request = Grpc_Testing_SimpleRequest.with {
Can we call this `message`? I think of the "request" as the overall input to the RPC, i.e. it includes the metadata as well. A "message" or "messages" are a part of the request.

2024-04-18 15:13 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +            _ = try response.message
```suggestion
          try await benchmarkClient.unaryCall(
            request: ClientRequest.Single(message: request)
          ) { response in
            _ = try response.message
```

2024-04-19 07:37 UTC, glbrntt requested changes
A few things got missed from last time but basically looks good!

2024-04-19 07:37 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +  enum RpcType {
nit: should be `RPCType`

2024-04-19 07:37 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +  ) throws {
This isn't throwing

2024-04-19 07:37 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +            response in
```suggestion
          ) { response in
```

2024-04-19 07:37 UTC, glbrntt commented on Sources/performance-worker/BenchmarkClient.swift
> +          _ = try await benchmarkClient.streamingFromClient(
This one shouldn't be necessary as the body of the closure doesn't return anything
```suggestion
          try await benchmarkClient.streamingFromClient(
```

2024-04-19 08:58 UTC, glbrntt approved these changes

2024-04-19 09:07 UTC, merged