Adopt `Mutex` where possible
grpc/grpc-swift pull request #2026
Opened 2024-08-21 09:48 UTC by glbrntt

Motivation:

Swift 6 has a `Mutex` which we can use in place of `LockedValueBox` or `NIOLockedValueBox` in a bunch of places.

Modifications:

- Use `Mutex` where possible
- This causes a number of other changes too as `Mutex` doesn't allocate: the allocations move to the type holding it instead. This makes sense as the objects which were previously structs didn't have value semantics.

Result:

Fewer uses of our own lock, no uses of NIOs lock

2024-08-27 16:01 UTC, gjcairo requested changes

2024-08-27 16:01 UTC, gjcairo commented on Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
> +internal import Synchronization
This can be `private`

2024-08-27 16:01 UTC, gjcairo commented on Sources/GRPCInProcessTransport/InProcessClientTransport.swift
> +internal import Synchronization
This can be `private`

2024-09-02 14:12 UTC, glbrntt commented on Sources/GRPCCore/Internal/Concurrency Primitives/Lock.swift
> -package struct LockedValueBox<Value> {
Not easily, `Mutex` doesn't have the manual `lock()`/`unlock()` methods which we rely on in `BroadcastAsyncSequence`. I want to look at that separately as that's likely to require a larger change.

2024-09-02 14:28 UTC, gjcairo approved these changes

2024-09-02 14:28 UTC, merged